[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1UJRBY26DIvBU1yQLGD9ZDZO7AKvaX2J-qBBw0VPLrOw/edit?usp=sharing"
[credenciales]
usuario_admin = "admin"
password_admin = "MiClaveSuperSegura"